#!/usr/bin/env python3
"""
udp_test_client.py

Send protobuf-encoded PanelCommand messages to the device UDP port (5000). Image resolution _must_ match
the panel size!

Usage examples:
  python3 util/udp_test_client.py 192.168.1.42 brightness --value 0.5
  python3 util/udp_test_client.py 192.168.1.42 demo --mode auto
  python3 util/udp_test_client.py 192.168.1.42 image --width 64 --height 96 --generate
  python3 util/udp_test_client.py 192.168.1.42 image --file image.bgr
  python3 util/udp_test_client.py 192.168.1.42 video --file video.mp4 --width 64 --height 96

Protobuf definitions are auto-generated from protos/panel.proto using protoc.
Generated files: util/panel_pb2.py, util/nanopb_pb2.py (generated by CMake during build).
"""

import argparse
import hashlib
import socket
import sys
import subprocess
import time
from pathlib import Path

import panel_pb2

DEMO_MODES = {
    'network': panel_pb2.PanelMode.PANEL_MODE_NETWORK,
    'auto': panel_pb2.PanelMode.PANEL_MODE_AUTO,
    'bouncing_balls': panel_pb2.PanelMode.PANEL_MODE_BOUNCING_BALLS,
    'fire': panel_pb2.PanelMode.PANEL_MODE_FIRE_EFFECT,
    'image': panel_pb2.PanelMode.PANEL_MODE_IMAGE_ANIMATION,
    'color': panel_pb2.PanelMode.PANEL_MODE_IMAGE_COLOR_CHECK,
}

def build_set_brightness(brightness: float) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.set_brightness.brightness = brightness
    return msg.SerializeToString()

def build_set_mode(mode: int) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.set_mode.mode = mode
    return msg.SerializeToString()

def build_set_image(rgb_bytes: bytes) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.set_image.image_data = rgb_bytes
    return msg.SerializeToString()

def build_set_base_brightness(brightness: int) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.base_brightness.brightness = brightness
    return msg.SerializeToString()

def build_firmware_upload(block: bytes) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.firmware_upload.firmware_data = block
    return msg.SerializeToString()

def decode_firmware_confirmation(block: bytes) -> bytes:
    msg = panel_pb2.PanelCommand()
    msg.ParseFromString(block)
    return msg.firmware_block_confirmation.block_hash

def send_udp_once(host: str, port: int, payload: bytes, index: int = 0):
    # Send single UDP datagram containing the protobuf payload (no length prefix)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(3)
    try:
        sent = sock.sendto(payload, (host, port))
        print(f"Sent {sent} bytes to {host}:{port} ({index})")
    finally:
        sock.close()

def generate_test_image(width: int, height: int) -> bytes:
    out = bytearray()
    for y in range(height):
        for x in range(width):
            r = x & 0xFF
            g = y & 0xFF
            b = (x + y) & 0xFF
            out.extend((r, g, b))
    return bytes(out)

def stream_video(host: str, port: int, video_file: Path, width: int, height: int, fps: float = 30.0, sock=None):
    """Stream video frames to device using ffmpeg"""

    if not video_file.exists():
        print(f"Video file not found: {video_file}")
        sys.exit(2)

    # ffmpeg command to decode and rescale video to RGB24
    cmd = [
        'ffmpeg',
        '-i', str(video_file),
        '-vf', f'scale={width}:{height}:force_original_aspect_ratio=decrease,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:black',
#        '-vf', 'transpose=0',
        '-pix_fmt', 'bgr24',
        '-f', 'rawvideo',
        '-r', str(fps),
        'pipe:1'
    ]
    print(cmd)
    try:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=0)
    except FileNotFoundError:
        print("ffmpeg not found. Please install ffmpeg: apt install ffmpeg (Debian/Ubuntu) or brew install ffmpeg (macOS)")
        sys.exit(2)

    frame_size = width * height * 3
    frame_count = 0
    frame_time = 1.0 / fps
    last_send_time = time.time()
    
    print(f"Streaming video to {host}:{port} at {fps} fps ({width}x{height})...")
    print("Press Ctrl+C to stop")
    
    try:
        while True:
            frame = proc.stdout.read(frame_size)
            if not frame or len(frame) < frame_size:
                break
            
            # Build and send image packet (single UDP datagram)
            pkt = build_set_image(frame)
            if sock is None:
                try:
                    send_udp_once(host, port, pkt)
                except Exception as e:
                    print(f"send failed: {e}")
                    break
            else:
                try:
                    sock.sendto(pkt, (host, port))
                except Exception as e:
                    print(f"send failed: {e}")
                    break
            frame_count += 1
            
            # Rate limit to fps
            elapsed = time.time() - last_send_time
            if elapsed < frame_time:
                time.sleep(frame_time - elapsed)
            last_send_time = time.time()
            
            if frame_count % 30 == 0:
                print(f"Sent {frame_count} frames")
    
    except KeyboardInterrupt:
        print(f"\nStopped. Sent {frame_count} frames total.")
    finally:
        proc.terminate()
        proc.wait()


def upload_firmware(host: str, port: int, file: Path, sock=None):
    """Upload firmware blocks to device"""

    if not file.exists():
        print(f"Firmware file not found: {file}")
        sys.exit(2)

    BUF_SIZE = 2048
    UF2_BLOCK = 512

    with open(file, 'rb') as f:
        data = f.read()

    data = bytearray(data)

    # Skip abs block
    data = data[UF2_BLOCK:]

    print("Len data", len(data), f"/{BUF_SIZE}", len(data) / BUF_SIZE)

    while (len(data) % BUF_SIZE != 0):
        data.extend([0] * UF2_BLOCK)

    print("Len data now", len(data), f"/{BUF_SIZE}", len(data) / BUF_SIZE)

    sock.bind(('0.0.0.0', port));
    sock.settimeout(0.5)

    # Repeat test for a number of iterations
    for i in range(len(data) // BUF_SIZE):
        print("I", i, "of", len(data) // BUF_SIZE, ' '*10, end='\r')
        uf2_buf = data[i*BUF_SIZE:(i+1)*BUF_SIZE]

        pkt = build_firmware_upload(bytes(uf2_buf))
        # Send the data back to the server
        retries = 0
        while retries < 10:
            retries = retries + 1
            send_udp_once(host, port, pkt, i)
            #write_len = sock.send(uf2_buf)
            #if write_len != BUF_SIZE:
            #    raise RuntimeError('wrong amount of data written')

            if i < (len(data) // BUF_SIZE) - 1:
                # Read 32 bytes from the server
                total_size = 36
                read_buf = b''
                try:
                    while total_size > 0:
                        buf = sock.recv(36)
                        if len(buf) == 0:
                            i = i - 1
                            continue
                        print('read %d bytes from server' % len(buf))
                        total_size -= len(buf)
                        read_buf += buf
                except TimeoutError:
                    print(f'Timeout waiting to ACK {i} ({retries})')
                    if retries >= 10:
                        raise TimeoutError()
                    else:
                        continue

                # Check size of data received
                if len(read_buf) != 36:
                    raise RuntimeError('wrong amount of data read %d', len(read_buf))

                read_buf = decode_firmware_confirmation(read_buf)

                # Check the hash matches
                h = hashlib.new('sha256')
                h.update(uf2_buf)
                if read_buf != h.digest():
                    print('buffer mismatch')
                    continue
                else:
                    print("Hash matched. Continuing.")
                    break
            if retries >= 10:
                print('Timeout')
                raise TimeoutError()


def main():
    parser = argparse.ArgumentParser(description='UDP protobuf test client for scoreboard')
    parser.add_argument('host', help='Device host or IP address')
    sub = parser.add_subparsers(dest='cmd', required=True)

    p_b = sub.add_parser('brightness')
    p_b.add_argument('--port', type=int, default=5000)
    p_b.add_argument('--value', type=float, required=True, help='Brightness 0.0..1.0')

    p_i = sub.add_parser('image')
    p_i.add_argument('--port', type=int, default=5000)
    group = p_i.add_mutually_exclusive_group(required=True)
    group.add_argument('--file', type=Path, help='Raw RGB888 file of size width*height*3')
    group.add_argument('--generate', action='store_true', help='Generate a test pattern')
    p_i.add_argument('--width', type=int, default=96, help='Image width (required for generate or validating file)')
    p_i.add_argument('--height', type=int, default=64, help='Image height')

    p_d = sub.add_parser('demo')
    p_d.add_argument('--port', type=int, default=5000)
    p_d.add_argument('--mode', choices=DEMO_MODES.keys(), required=True, help='Demo mode to set')

    p_bb = sub.add_parser('base-brightness')
    p_bb.add_argument('--port', type=int, default=5000)
    p_bb.add_argument('--value', type=int, required=True, help='Base brightness (0-255)')

    p_fota = sub.add_parser('fota')
    p_fota.add_argument('--port', type=int, default=5000)
    p_fota.add_argument('--file', type=Path, required=True, help='.uf2 firmware file')

    p_v = sub.add_parser('video')
    p_v.add_argument('--port', type=int, default=5000)
    p_v.add_argument('--file', type=Path, required=True, help='Video file to stream')
    p_v.add_argument('--width', type=int, default=96, help='Output video width')
    p_v.add_argument('--height', type=int, default=64, help='Output video height')
    p_v.add_argument('--fps', type=float, default=30.0, help='Frames per second')

    args = parser.parse_args()
    if args.cmd == 'brightness':
        v = float(args.value)
        if v < 0.0 or v > 1.0:
            print('Brightness must be between 0.0 and 1.0')
            sys.exit(2)
        pkt = build_set_brightness(v)
        send_udp_once(args.host, args.port, pkt)
        print(f'Sent brightness={v} to {args.host}:{args.port} (UDP)')

    elif args.cmd == 'image':
        w = args.width
        h = args.height
        if args.file:
            data = args.file.read_bytes()
            expected = w * h * 3
            if len(data) != expected:
                print(f'File size {len(data)} does not match expected {expected} (width*height*3)')
                sys.exit(2)
            rgb = data
        else:
            rgb = generate_test_image(w, h)
        pkt = build_set_image(rgb)
        print(f'DEBUG: image protobuf payload hex (first 50 bytes): {pkt[:50].hex()}')
        print(f'DEBUG: total payload size: {len(pkt)} bytes')
        send_udp_once(args.host, args.port, pkt)
        print(f'Sent image {w}x{h} ({len(rgb)} bytes) to {args.host}:{args.port} (UDP)')

    elif args.cmd == 'demo':
        mode = DEMO_MODES[args.mode]
        pkt = build_set_mode(mode)
        send_udp_once(args.host, args.port, pkt)
        print(f'Sent demo mode={args.mode} ({mode}) to {args.host}:{args.port} (UDP)')

    elif args.cmd == 'base-brightness':
        v = int(args.value)
        if v < 0 or v > 255:
            print('Base brightness must be between 0 and 255')
            sys.exit(2)
        pkt = build_set_base_brightness(v)
        send_udp_once(args.host, args.port, pkt)
        print(f'Sent base_brightness={v} to {args.host}:{args.port} (UDP)')

    elif args.cmd == 'video':
        # Open UDP socket for streaming
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            stream_video(args.host, args.port, args.file, args.width, args.height, args.fps, sock=sock)
        finally:
            try:
                sock.close()
            except Exception:
                pass

    elif args.cmd == 'fota':
        # Open UDP socket for firmware update
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            upload_firmware(args.host, args.port, args.file, sock=sock)
        finally:
            try:
                sock.close()
            except Exception:
                pass

    else:
        parser.print_help()

if __name__ == '__main__':
    main()
